### PR TITLE
Add a way to access the contents of an erroneous line

### PR DESCRIPTION
**Pull request by jwpjrdev**
If there's currently a way to do this, I'm unaware of it

### CODE REVIEW

**Comment by tomtau** [comment]
I think it's possible to access error lines indirectly, plus there are issues that may possibly lead to changes in internal representations (e.g. https://github.com/pest-parser/pest/issues/589 ). While this is a trivial change, I'm not sure whether it's ok to make the field public, given it could break in the near future (if the indirect access isn't ok, perhaps just add a getter for &str instead?).
@CAD97 what do you think?

**Comment by jwpjrdev** [comment]
Interesting. If they're fine with it, I'll do that.

**Comment by CAD97** [comment]
A `.line() -> &str` would probably be the better approach, yeah.

**Comment by jwpjrdev** [comment]
Had a git noob moment and accidentally ended up with this PR being closed

**Pull request closed without merging**
