### PR TITLE
Migrate from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by MaxBondABE**
Migrate CI logic from Travis to equivalent GHA access.

Solves #482 

- Commits in this PR should be squashed during merge. There's a lot of noise in the commit history because I had to push commits to trigger GHA for debugging.
- The Fuzzit API key should be added to the Github Secrets repository under the name `FuzzitApiKey`

### CODE REVIEW

**Comment by MaxBondABE** [comment]
I've incorporated feedback from @CAD97 and am marking this PR as ready for review.

**Comment by dragostis** [comment]
This looks good. Thank you so much for fixing this. 😃 

bors r+

**Comment by CAD97** [comment]
We need to set up bors to look at the GHA feedback, so I'm merg-squishing this manually such that we can do so.

**Comment by CAD97** [comment]
First workflow run: https://github.com/pest-parser/pest/actions/runs/397209051

**Comment by CAD97** [comment]
@dragostis we need to set `$FUZZIT_API_KEY` in the GHA secrets still.

**Comment by MaxBondABE** [comment]
> We need to set up bors to look at the GHA feedback, so I'm merg-squishing this manually such that we can do so.

Thanks for merging!

I'll work on the `bors` portion this weekend. Should have it down by the 14th.

**Comment by dragostis** [comment]
@CAD97, I added the secret, but it seems to fail with a 404.

**Comment by dragostis** [comment]
@MaxBondABE, do you have any idea why the fuzzing is broken?

**Comment by MaxBondABE** [comment]
@dragostis I apologize it's taken me a couple of days to get back to you, I was detained by other matters.

I briefly looked into this but have not figured it out yet. Foolishly I didn't upload any testcases to Fuzzit when I tested in my fork, and so didn't encounter this issue.

I'll have some time tomorrow to spend on this.

**Pull request merged**
