### PR TITLE
Fix a documentation formatting glitch (Ugly, but \ does not work in b…

### PR DESCRIPTION
**Pull request by lwandrebeck**
…ackticks)

### CODE REVIEW

**Comment by jstnlef** [comment]
Hrm. I'm not sure what you're seeing. The original looks fine to me. Maybe post a screenshot?

**Comment by dragostis** [comment]
@jstnlef There is an issue in [pulldown-cmark](https://github.com/google/pulldown-cmark/issues/127).

**Comment by lwandrebeck** [comment]
@jstnlef see https://docs.rs/pest_derive/1.0.6/pest_derive/#Grammar , non-terminals.
It is an issue with markdown renderer, and it don’t look that much that they are willing a lot to fix that.

**Comment by jstnlef** [comment]
Oh I see. I must have been building the docs locally with the other renderer.

**Comment by lwandrebeck** [comment]
From 1.25 Announce :
« Second, back in Rust 1.23, we talked about the change from Hoedown to pulldown-cmark. In Rust 1.25, pulldown-cmark is now the default »

**Comment by wirelyre** [comment]
This can also be fixed like so:

```markdown
| <code>e1 \| e2</code> | matches either `e1` or `e2` |
```

The other rows can use backticks as before.

**Comment by dragostis** [comment]
I'll close this PR in favor of @wirelyre's fix.

**Pull request closed without merging**
