### PR TITLE
Procedural macros complete refactoring.

### PR DESCRIPTION
**Pull request by dragostis**

### CODE REVIEW

**Comment by sunjay** [comment]
Does this mean that once this lands this won't work on stable anymore?

**Comment by dragostis** [comment]
It will work on stable. Rust 1.15 will come with custom derive support.

**Comment by sunjay** [comment]
Great! Really excited for this! :+1:

**Comment by dragostis** [comment]
@sunjay Pretty excited too. I'm satisfied with the current optimizations strategies and will focus on code generation right now. Any code review is more than welcome. :smile:

**Comment by Keats** [comment]
Is it ready minus integration tests/examples? Looking forward to it!

**Comment by dragostis** [comment]
@Keats Not quite. I'm currently tuning performance. After that, I'll need to do the generation.

**Comment by Keats** [comment]
Maybe we can try the latest rustfmt on the code as well, it will change the visual indent to block indent though.

**Comment by dragostis** [comment]
@Keats I've tried that before, but I'm not a big fan of the trailing commas and there was no way to remove them from all the places. However, I'm definitely for using rustfmt. I'll give the latest version a trey and see how it works.

**Comment by sphinxc0re** [comment]
@dragostis Are you still actively working on this? I would really like to build a c-parser using pest and such a parser would profit massively from this refactor.

**Comment by dragostis** [comment]
@sphinxc0re Yes, but I'd argue that it's currently alpha quality. Unfortunately, I'm still hacking on the documentation for the grammar and the derive, but there are some grammar examples in [`pest_grammars`](https://github.com/pest-parser/pest/tree/procedural/pest_grammars). Join us on [Gitter](https://gitter.im/pest-parser/pest) and I'll gladly help you out. 😃

**Pull request merged**
