### PR TITLE
travis: add a build with minimum dependencies

### PR DESCRIPTION
**Pull request by Keruspe**
This allows us to test if our lower bounds are correct

### CODE REVIEW

**Comment by Keruspe** [comment]
A 2.0.1 release of generator with this change would allow to go further and make the build go green

**Comment by dragostis** [comment]
Thanks for the PR! In order to apply this, one would need to merge, release, then re-run Travis, correct?

**Comment by Keruspe** [comment]
Well, as it’s a nightly run, failures are allowed, so first step would be
merging this, then release, then iterate on this to make it pass.
This won’t fix the new clippy failures on stable that appeared with the
1.31 release though

**Comment by CAD97** [comment]
Hey! #315 has been pruned back to be merged now, and basically rewrites the Travis matrix. I took the liberty of going ahead and inserting a `minimal-versions` job into it. It'll require a rebase from you, though, to resolve with the new matrix.

It should be as simple as just accepting the upstream `.travis.yml` assuming I did my job correctly :)

**Comment by CAD97** [comment]
Alright, thanks for this! It'd be _really_ nice if we can help more crates in the ecosystem not lie about minimal dependencies. (I really should set up this build job on some of my own crates.)

With some shenanigans, I can confirm that once bootstrap is pointing at `generator:2.0.1`, the minimal-versions build passes. I'm opening #357 to record that change and gate CI on it.

bors: r+

<details><summary>shenanigans</summary>

```sh
cargo bootstrap
mv target/debug/pest_bootstrap pest_bootstrap
cargo clean
mv pest_bootstrap target/debug/pest_bootstrap
edit bootstrap/Cargo.toml # pest_generator = { version = "2.0.1", path = "../generator" }
cargo +nightly -Z minimal-versions generate-lockfile
cargo bootstrap
cargo test --all
```

**Pull request merged**
