### PR TITLE
Fix clippy errors

### PR DESCRIPTION
**Pull request by CAD97**
Prerequisite to enabling clippy on CI (#295, #310).

cc @luizdepra (feel free to pull this into #310)

### CODE REVIEW

**Comment by CAD97** [comment]
Actually, this changes some `pub` fn, so someone needs to go through and check whether these are exported (thus breaking changes to change) and allow for those instead. I just naively did the `&Vec<...>`->`&[...]` transformation for those.

**Comment by CAD97** [comment]
The actually breaking changes (just did a quick check):

- `pest_meta::validator::validate_rust_keywords`
- `pest_meta::validator::validate_pest_keywords`
- `pest_meta::validator::validate_already_defined`
- `pest_meta::validator::validate_undefined`
- `pest_meta::validator::validate_ast`

We have three options: bump the `pest_meta` version, change them back and allow the lint, or change them back, allow the lint, deprecate them, and make new versions that take slices.

**Comment by dragostis** [comment]
Deprecating is a bit unfortunate since you'll have two almost identical versions in the docs, but I guess it makes most sense.

**Comment by luizdepra** [comment]
@CAD97, ok. Waiting the merge.

**Comment by CAD97** [comment]
Wait we don't have bors set up 😆 I'll merge when green manually then

**Pull request merged**
