### PR TITLE
feature: unary prefix/suffix operator support via PrattParser

### LINKED ISSUE #461: make PrecClimber support prefix and postfix operators
## Problem

The PrecClimber handles precedence between infix operators, like `a + b * c`, but doesn't handle precedence between prefix or postfix operators, like `-a.b + c`.

## Expectation

The PrecClimber should be able to resolve prefix and postfix operators along with infix operators.

### PR DESCRIPTION
**Pull request by tomtau**
Closes #461

based on #344

Co-authored-by: @segeljakt

### CODE REVIEW

**Comment by tomtau** [comment]
@pest-parser/maintainers is it ok to merge and release it? It's non-breaking, but not sure if marking `PrecClimber` deprecated right away is ok

**Comment by NoahTheDuke** [comment]
Sorry, been busy. Is there any reason to deprecate the old parser instead of letting it live side by side?

**Comment by tomtau** [comment]
> Sorry, been busy. Is there any reason to deprecate the old parser instead of letting it live side by side?

because it's a duplicate -- `PrattParser` can do what `PrecClimber` can do, but is more general (so it can handle more cases, such as unary ops)

**Comment by NoahTheDuke** [comment]
If it's purely additive, is there any reason to rename it? Or is the api fundamentally different somehow?

**Comment by tomtau** [comment]
> If it's purely additive, is there any reason to rename it? Or is the api fundamentally different somehow?

The API is different. See e.g. the calculator test: https://github.com/pest-parser/pest/pull/710/files#diff-e2dbd27540c35bdae26743d1b758d99b1186ec63a0be6abc83dfd4ca70c571edR132

**Comment by tomtau** [comment]
(plus the original PR's comments: https://github.com/pest-parser/pest/pull/344#issuecomment-489008650 )

**Review by NoahTheDuke — CHANGES_REQUESTED** [review]
Okay, I've had a chance to read through the code. I'm glad to see that the changes to Pest internals are minimal. Overall, this is a good PR and I think it should be merged. Two thoughts:

This might be my Clojure background coming out but I think we should make it clear that we're not going to remove PrecClimber in a future version, just marking it as less powerful/useful than PrattParser. It's important that people can trust the code they write today will still work in the future, even across multiple versions.

I also think that the internal method names `nud`, `led`, and `lbp` are quite terse. I have no idea what they stand for, lol. Given that they're only used internally and only in one place, I think they should get more descriptive names, ideally with at least minimal docstrings.

Thanks so much for getting this cleaned up!

**Review by NoahTheDuke — APPROVED** [review]

**Comment by tomtau** [comment]
@NoahTheDuke thanks! I extended the deprecation note.
As for the internal methods, I kept them, but added doc strings on them to explain what they stand for. While those terse names are a bit scary, they are ubiquitous in Pratt parser implementations (given that's what the [original 1973 paper](https://web.archive.org/web/20151223215421/http://hall.org.ua/halls/wizzard/pdf/Vaughan.Pratt.TDOP.pdf) used).

**Pull request merged**
