### PR TITLE
Add more optimizations

### PR DESCRIPTION
**Pull request by SkiFire13**
Adds a couple more optimizations:

1. Converts `(rule ~ rest) | rule` to `rule ~ rest?`, avoiding trying to match `rule` twice. Same as the already existing `factor` but in the case the second expression is not `Expr::Seq`.

2. Converts `rule | (rule ~ rest)` to `rule` since `(rule ~ rest)` will never match if `rule` didn't. Not sure if this should go in `factorizer.rs` but the pattern looked really similar.

3. Converts `(rule ~ rest)* ~ rule` to `rule ~ (rest ~ rule)*`, avoiding matching the last `rule` twice, should have a big impact on issues like #453 and #463. Goes to a new file names `lister.rs`, not sure if the name is descriptive enough.

Actually there's a 4th optimization I thought of, converting `(rule ~ rest)* ~ rule?` to `rule ~ (rest ~ rule)* ~ rest?`, assuming `rule` is more expensive than `rest` but I don't think this can be determined if one of them contain an `Expr::Ident`. This would have the same effect of 3. on the relevant cases.

### CODE REVIEW

**Review by dragostis — CHANGES_REQUESTED** [review]
Thanks a lot for taking time to write this! The change looks good, but I'd like to ask you to write some tests for this before merging.

**Review by dragostis — APPROVED** [review]
Neat! Again, thanks a lot for this. 👍 

bors r+

**Comment by CAD97** [comment]
I'll re-r this once CI is fixed (#483), but I unfortunately really don't have time to sort through the new style warnings and apply/ignore them right now. <sub>I already spent too much time on this, grad school is really eating all of my time</sub>

**Review by CAD97 — CHANGES_REQUESTED** [review]
Fix the merge issue and I'll merge this.

**Review by CAD97 — APPROVED** [review]
bors r=dragostis

Will manually merge when CI passes

**Comment by MarinPostma** [comment]
bors merge

**Pull request merged**
