### PR TITLE
fix: decrease a call limit on the toml fuzzer

### LINKED ISSUE #697: oss-fuzz: toml stackoverflow crash
**Describe the bug**
toml fuzzer crashes on stackoverflow again

**To Reproduce**
Minimal sample:
```
[1]O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=5,z=8,Ox4=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=4294967297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=5,z=8,Ox4=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=4294967297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=5,z=8,Ox4=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=4294967297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=5,z=8,Ox4=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=4294967297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=5,z=8,Ox4=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=6,O=0,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=0,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=4294967297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[7297,O=8,x=6,O=5,z=8,Ox3r=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[{x=1,O=8,x=5,O=5,z=8,Ox3=[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1,5,

[1,5
,5
,170141183460469231731687303715916988704O=8
```

**Expected behavior**
Not crash.

**Additional context**
https://oss-fuzz.com/testcase-detail/6224311978950656

### PR DESCRIPTION
**Pull request by tomtau**
closes #697

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
Weird that it's failing now but wasn't failing earlier. Looks like this sample is truly a worst case scenario. Should the limit be lowered even more?

**Comment by CAD97** [comment]
Ideally we'd determine what the actual limit is to avoid an OOM. And ideally max usage should be linear on the limit, so there shouldn't be a case where one input hits the limit but another OOMs...

**Comment by CAD97** [comment]
(Meta note: I don't know why the maintainers review request is being converted to an individual but the team isn't.. perhaps it's the fact that the requested maintainer is also on the triage team? But then why do I have a requested review? I think what's happened is that GH has routed the triage request to me but not updated that in the reviewers list?)

**Comment by tomtau** [comment]
@NoahTheDuke this one is weird that I managed to reproduce it locally (the sample crashes even VSCode's parser sometimes when I try to open it), but the limit I set passes on my machine locally, but fails on CI for some reason

**Comment by tomtau** [comment]
@NoahTheDuke when running the tests with `--release` on CI, it seems to work fine: https://github.com/pest-parser/pest/actions/runs/2876875272

**Comment by tomtau** [comment]
@CAD97 I'd prefer the `#[ignore]`, because I wasn't able to reliable reproduce the CI behaviour locally in the debug mode (i.e. tests didn't crash with the set limit, unlike CI), so there may be a few more runtime and toolchain variables than just the optimization level. Unfortunately, `--include-ignored` fails due to a handful of ignored illustratory doc examples that don't build (one alternative for them may be to change them to `text` instead of `ignore`, but that would lose syntax highlighting).

Anyway, let's go with the second option for now (I feature-guarded that problematic sample execution with `#[cfg(not(debug_assertions))]`).

**Comment by CAD97** [comment]
> Unfortunately, `--include-ignored` fails due to a handful of ignored illustratory doc examples that don't build

And unfortunately the rustdoc team isn't very open to [fixing this](https://github.com/rust-lang/rust/pull/96573) for some reason. The interim solution is to specify which tests to include manually, using e.g. smth like `test -- --ignored exhaustion_limits`.

**Comment by tomtau** [comment]
@CAD97 ok, thanks for the context. Yes, we can then keep it ignored with a separate step to run `-- --ignored ...` for the moment then.

**Comment by tomtau** [comment]
@NoahTheDuke @CAD97 ok to merge this?

**Review by NoahTheDuke — APPROVED** [review]

**Review by CAD97 — APPROVED** [review]
Lgtm now

**Pull request merged**
