### PR TITLE
Update mod.rs

### PR DESCRIPTION
**Pull request by TheVeryDarkness**
Fix an error of implementation of Display for OptimizedExpr, which will break the line when it contains a control character such as \n or \r.

### CODE REVIEW

**Review by tomtau — APPROVED** [review]
@TheVeryDarkness it seems ok -- can you perhaps add unit tests that demonstrate the bug this change fixed?

**Comment by TheVeryDarkness** [comment]
@tomtau yes, I add several tests and add some improvement to my implementation.
By the way, I also implemented Display for Expr just now :)

**Comment by TheVeryDarkness** [comment]
I'm wondering why github is showing the commit from another branch **master** but not **patch2**, which is used to deal with Display.

**Comment by TheVeryDarkness** [comment]
Oops, I create the new branch based on my working branch by mistake. I'll create a new branch and a new pull request then.

**Pull request closed without merging**
