### PR TITLE
fix: Limit error messages new line visualization (fixes #362)

### LINKED ISSUE #362: Error messages include ␊ on all lines
https://github.com/pest-parser/pest/commit/95881fd2e3a4fc278f73326b5a86b079eda41d24 changed `Error` so that both `new_from_pos` and `new_from_span` variants have `visualize_whitespace` called.  Prior to this, only `new_from_pos` variants had their whitespace visualized.

This has the side-effect of making *all* error messages include replacement symbols for their terminating newline.  You can see this on the pest editor here: https://pest-parser.github.io/?bin=18hayc#editor

```
 --> 1:1
  |
1 | goodbye␊
  | ^---
  |
  = expected hello
```

The extra LF symbol (␊) is confusing for end users, and is noise in cases like this where whitespace is irrelevant.  I would expect CR and NL to only be visualized when they are important to the error.

### PR DESCRIPTION
**Pull request by tomtau**
`new_from_pos` and `new_from_span` only visualize newline
characters if positions point to the newline characters.

### CODE REVIEW

**Comment by glyn** [comment]
Will conditional handling of newline characters violate the principle of least surprise? Maybe an example, before and after this fix, would demonstrate that isn't the case.

**Comment by CAD97** [comment]
This change (should) only impacts error rendering. When showing a snippet of source, the newlines are still visible as, well, newlines. The addition of `␊` is only needed for an error span to point at the newline character itself.

One potential source of confusion is if `␊` appears literally in the source. This PR (should) only make things better in this case, as it removes insertion of `␊` when it is not necessary in order to be able to point directly at the `␊`.

**Comment by glyn** [comment]
Ok, sounds reasonable. Thanks. @tomtau feel free to add an example if you think it clarifies things.

**Comment by CAD97** [comment]
(I assigned `@pest-parser/triage`, which is set to automatically load-balance review requests. Feel free to reassign if you don't want to review. If we get a LGTM/Approve review from triage and CI is green I'll hit the merge button.)

**Comment by jhpratt** [comment]
Yeah, I haven't had a chance to look through any of the code yet, so I wouldn't know what I'm looking at at this point.

**Review by CAD97 — APPROVED** [review]
In retrospect I'm not completely certain I agree with the choice to visualize LF in this manner, but this is clearly an improvement on the status quo.

**Comment by tomtau** [comment]
@glyn one of the error tests has an example where the `␊` character is visualized  https://github.com/pest-parser/pest/blob/96eace8c69e4258789708ff796e679b8f3f48ace/pest/src/error.rs#L774 because the error position points to `\n`, while some of the other error tests were fixed not to visualize the newline characters in their examples, because their positions didn't point to `\n` or `\r`.

**Pull request merged**
