### PR TITLE
Adding qubit in "Projects using pest"

### PR DESCRIPTION
**Pull request by abhimanyu003**
Hello Team,
Thanks so much for your work on pest.

I'm adding qubit as Projects using pest.
Github link https://github.com/abhimanyu003/qubit
Live https://abhimanyu003.github.io/qubit/

I hope you allow it. 

Thanks

### CODE REVIEW

**Comment by nathanielknight** [comment]
This looks good, thanks for the PR :+1:

**Comment by CAD97** [comment]
Sorry for the delay! If you fix the merge conflict we'd be happy to merge this.

**Comment by abhimanyu003** [comment]
Sure adding #587 in a bit @tomtau

**Comment by abhimanyu003** [comment]
Added #587 ( melody ) to the list.

**Pull request merged**
