### PR TITLE
Add `input_range` method to `Pair`.

### PR DESCRIPTION
**Pull request by jamesotron**
Initially I was going to make `pos()` public, but then I decided that since `Pair` had a reference to `input` then would be better to just have it expose `line_col` instead, since that was the ultimate goal for me.

### CODE REVIEW

**Comment by dragostis** [comment]
This is not quite right since a `Pair` can will usually span over multiple columns, maybe even lines. Do you perhaps want to find the line and column of the starting position of the `Pair`?

**Comment by jamesotron** [comment]
Yes, I was trying to find the starting position, although now that you mention it could be quite useful to get the end position also.  I need this information to show the user non-parsing-related error messages during compilation.

**Comment by dragostis** [comment]
It may be a better idea to expose the start and end position.

**Comment by jamesotron** [comment]
I've exposed the start and end position of the `Pair` in the input, however I'm concerned about https://github.com/jamesotron/pest/commit/c0ed4ddc7999d98170f3974de18de78973bc1d46#diff-bb8e329f6a128880f3a917e70c24ea14R230 - it appears that the end position of each token is advanced by one.

**Comment by dragostis** [comment]
I'm closing this since the functionality is available through `Pair::into_span`.

**Pull request closed without merging**
