### PR TITLE
fix CI workflows

### PR DESCRIPTION
**Pull request by MarinPostma**
This pr attempts to fix the issues encoutnered with the migration of the CI from travis to github actions. The issues that have been solved are:
- Install gcc, libssl-edv and pkg-config to the recipes that needed it.
- Install minimal rust toolchains for nightly, since they don't come with rust-fmt or clippy
- fix all clippy warn

### CODE REVIEW

**Comment by CAD97** [comment]
Thanks for this!

This looks good to r=me now (fuzz tests are known failure, honestly should be disabled for now, and aren't checked by bors), but I'll hold off until you think it's good (mark the PR as not a draft).

**Comment by CAD97** [comment]
I don't know if public bors supports this but may as well try

bors: d+

**Comment by CAD97** [comment]
(And the full version)

bors: delegate+

**Comment by MarinPostma** [comment]
@CAD97 could you re-enable fuzzing? I could run them locally using https://github.com/nektos/act, so I wonder if they run now

**Comment by meiamsome** [comment]
Looks like this fixes #505 and #490

**Comment by CAD97** [comment]
(sorry for the delay)

This does seem to fix fuzzing as well! The task is still being run, Bors just isn't gated on it. I'll regate bors on it later this week probably.

Thanks for your work!

bors: r+

**Pull request merged**
